### PR TITLE
KIN-297 edit certificate page layout certificates page

### PR DESCRIPTION
**Pull request by FernandoJoachin**
[KIN-297](https://loopcrack.atlassian.net/browse/KIN-297) Small [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

### Problem

As a company I would like to be able to edit a certificate in the system in the administration panel.

### Solution

Create a certificate editing view on the admin panel page so that you can edit a certificate on the system.

### Requirements checklist

- [x] The create button  on the certificates page view should redirect to a page with a form to register a new certificate..
- [x] The form must get the following info: Certificate name, Certificate image preview and Certificate file.
- [x] The form must have a submit button.
- [x] It must show a response when edited the certificate indicating success or failure in the process.

### Testing

- [x] Click on the edit button on the certificates page

## Demo
[](https://postimg.cc/vg5wz2m9)

[KIN-297]: https://loopcrack.atlassian.net/browse/KIN-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CarlosMay7 — APPROVED** [review]

**Review by CheloChidoone — APPROVED** [review]
Good Job @FernandoJoachin, looks good.

**Review by Oswaldo-Chan — APPROVED** [review]
Good job @FernandoJoachin!

**Review by Mauriciocr207 — APPROVED** [review]
Good job!

**Review by LUGAMAFE — APPROVED** [review]
Nice!

**Pull request merged**
