### PR TITLE
KIN-79 Implemented the About Us section on the Home page

### PR DESCRIPTION
**Pull request by CarlosMay7**
[KIN-79](https://loopcrack.atlassian.net/browse/KIN-79) Medium [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

### Problem

The homepage needs to express the audience some information to learn about the company and who they are in order to connect and create a closer relation with the client

### Solution

Creating a section in the home page that describes some facts about them and other relevant information related to it can be the way to reach the goal

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [x] It should be responsive
- [x] It must contain a header
- [x] It must contain support for .webp and .avif images

Text related to the section.
### Testing

Describe any tests (manual or automated) executed to verify your changes

- [x] Use browser development tools to simulate sizes of different devices

## Resources

- https://responsively.app

## Demo

image
image
image

[KIN-79]: https://loopcrack.atlassian.net/browse/KIN-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Oswaldo-Chan — CHANGES_REQUESTED** [review]
I recommend changing the HTML classes to English, and also adding the HTML code to support the AVIF and WEBP versions of the image in the section

**Comment by LUGAMAFE** [comment]
@CarlosMay7 lo desarollado no se parece en varias cosas al diseño, https://drive.google.com/drive/folders/1_NNoqi7631tk9s7BbQoStycmSvTemprS?usp=sharing

el texto de nosotros deberia estar alineado a la derecha, el color de la fuente del texto, la separacion entre lineas, font weight y tamaño no parece similar al del diseño.

El border radius de la esquina inferior derecha tampoco da en el punto como en el diseño, en el diseño no es tan pronunciado y la esquina superior derecha no tiene un border radius.

tambien en el responsive la separacion entre el texto e imagen no es el correcto, tambien podriamos cambiar el tamaño de la fuente para que se viera mejor.

**Review by CarlosJCD — COMMENTED** [review]
On the requirements checklist, I think it should not be any problem if we dispose the "related image" checkmark because that is something that the client must provide. Am I right? @LUGAMAFE @CheloChidoone

**Comment by LUGAMAFE** [comment]
@CarlosMay7 manten la alineacion a la derecha en vistas mobiles y aumenta el espaciado entre las imagenes y texto ya que visualmente se ve feo 
image
image

**Review by LUGAMAFE — CHANGES_REQUESTED** [review]
Hay que corregir lo de las alineaciones antes de cerrar el PR

**Review by CheloChidoone — APPROVED** [review]

**Review by LUGAMAFE — APPROVED** [review]

**Review by Oswaldo-Chan — APPROVED** [review]

**Review by FernandoJoachin — APPROVED** [review]

**Pull request merged**
