### PR TITLE
Feature/kin 76/footer public view front end

### PR DESCRIPTION
**Pull request by CarlosMay7**
[KIN-76](https://loopcrack.atlassian.net/browse/KIN-76) Medium [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

### Problem

The company needs an space where the clients can reach more social networks related to them and also check a privacy advice.

### Solution

Creating a footer section at the end of each public page that contains the company's social networks and the privacy advice.

### Requirements checklist

- [x] It must be displayed on each public page of the website.

It must contain links to the following social networks:

- [x] Youtube

- [x] LinkedIn

- [x] Facebook

- [x] instagram

- [x] The links must be logos of the social networks to which they respectively lead.

- [x] The link should open in a new tab, not replace the current tab.

### Testing
- [x] Check the links redirections manually

## Demo
image
image
image

[KIN-76]: https://loopcrack.atlassian.net/browse/KIN-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CheloChidoone — CHANGES_REQUESTED** [review]
@CarlosMay7 No se ve mal pero hay varias cosas diferentes al [diseño original](https://drive.google.com/drive/folders/1_NNoqi7631tk9s7BbQoStycmSvTemprS?usp=sharing).

- Los botones de redes sociales deben estar en el centro del footer en cualquier tamaño de pantalla
- El enlace de Aviso de privacidad debe estar alineado abajo y a la izquierda del footer en cualquier tamaño de pantalla
- En Aviso de privacidad solo la primera A de aviso es mayúscula, todo lo demás en minúscula
- Los iconos que elegiste para los botones no son los mismos que están en el diseño
- En el diseño solo hay 4 botones de footer, el de twitter no esta agregado

**Comment by CarlosMay7** [comment]
Changed the buttons disposition, the privacy advice alignment and writing, the icons and deleted the ectra twitter button

**Review by Mauriciocr207 — APPROVED** [review]

**Review by CheloChidoone — APPROVED** [review]
Gracias por las correcciones, quedo mejor.

**Review by Oswaldo-Chan — APPROVED** [review]

**Comment by LUGAMAFE** [comment]
@Oswaldo-Chan please just make sure that the name of this PR is correct should be something like:
 KIN-76 footer public view front end

**Comment by LUGAMAFE** [comment]
@CarlosMay7 in the same way i noticed that the responsive view for the galaxy fold is incorrect, lets try that all this page can be viewed on this device please

**Review by LUGAMAFE — APPROVED** [review]

**Review by CarlosJCD — APPROVED** [review]

**Comment by LUGAMAFE** [comment]
@CarlosMay7 el nombre de tu PR porfas deberia ser algo asi como KIN-76 footer public view front end

**Pull request merged**
