### PR TITLE
KIN-122 Edit product view products page frontend 

### PR DESCRIPTION
**Pull request by LUGAMAFE**
[KIN-122](https://loopcrack.atlassian.net/browse/KIN-122) Medium [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

### Problem

As a company I want to be able to edit the information of a product through a form with the product information so that the product info can be corrected or updated.

### Solution

Provide an interface where edit a product information

### Requirements checklist

- [x] It must display the same page content stated on create product view
 but with the fields containing the information of the product that is wished to edit. 

### Testing

- [x] Remember do `php spark migrate:refresh` and `php spark db:seed MainTestSeeder` to get the longtext type on the `productDescription` and `productDetails` fields on db.
- [x] go to `/admin/productos`, create a product in order to not get conflicts with a product files. Then you can go to edit that created product and see all information you save on product. 

## Demo

[KIN-122]: https://loopcrack.atlassian.net/browse/KIN-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CarlosJCD — APPROVED** [review]
Nice work, just check out @CheloChidoone requested changes

CC: @CheloChidoone

**Review by CheloChidoone — CHANGES_REQUESTED** [review]
@Mauriciocr207 From the List of changes we need after the demo, two can be checked in this PR I think:

- We need to move the `video principal` input to where the `area de descargas` inputs are since that video is the one that appears in `area de descarga`
- We need to eliminate the option to add images from both wysiwyg

**Comment by Mauriciocr207** [comment]
> @Mauriciocr207 From the List of changes we need after the demo, two can be checked in this PR I think:
> 
> * We need to move the `video principal` input to where the `area de descargas` inputs are since that video is the one that appears in `area de descarga`
> * We need to eliminate the option to add images from both wysiwyg

Also,  it is not necessary to change the productDescription to longtext type right?

**Review by Cristianpan — APPROVED** [review]

**Review by Oswaldo-Chan — APPROVED** [review]

**Review by CheloChidoone — APPROVED** [review]
Good Job @Mauriciocr207

**Pull request merged**
