### PR TITLE
KIN-281 new css architecture and home refactor

### PR DESCRIPTION
**Pull request by LUGAMAFE**
[KIN-281](https://loopcrack.atlassian.net/browse/KIN-281) Massive [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

# Pull Request Template

## Summary

This PR introduces the implementation of ITCSS, Atomic Design, and BEM methodologies in the project. It aims to standardize and optimize the frontend CSS architecture, improving maintainability and scalability.

## Problem

The frontend development lacked standardized methodologies for CSS architecture, leading to potential inconsistencies and maintainability issues.

## Solution

- Implement **ITCSS (Inverted Triangle CSS)** for scalable and maintainable CSS architecture.
- Apply **Atomic Design** principles for systematic UI construction.
- Use **BEM (Block Element Modifier)** for class naming conventions, ensuring readability and reusability.
- Provide comprehensive documentation for each methodology.

## Acceptance Criteria

- [x] ITCSS structure implemented and documented.
- [x] BEM Methodology integrated and documented.
- [x] The home page CSS refactored to align with the new CSS architecture (KIN-339).

## Testing

Rememeber do `npm install `

- [x] Test the implementation on the home page to ensure compliance with ITCSS and Atomic Design rules.
- [x] Cross-browser testing to verify CSS consistency across different browsers. 
- [x] Mobile-responsive testing to ensure the UI adapts correctly on various devices.

## Resources

- [ITCSS: Scalable and Maintainable CSS Architecture](https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/)
- [Harry Roberts - Managing CSS Projects with ITCSS](https://www.youtube.com/watch?v=1OKZOV-iLj4)
- [BEM Methodology](https://en.bem.info/methodology/)
- [CSS Methodologies and Architectures: OOCSS, BEM, SMACSS, ITCSS, Atomic Design](https://medium.com/williambastidasblog/metodologías-o-arquitecturas-css-oocss-bem-smacss-itcss-atomic-design-a1a3cfbfa6c9)
- [Atomic Web Design by Brad Frost](https://bradfrost.com/blog/post/atomic-web-design/)
- [ITCSS: What is it and its foundations](https://desarrolloweb.com/articulos/itcss-que-es-bases.html)
- [CSS Container Queries](https://developer.mozilla.org/es/docs/Web/CSS/CSS_container_queries)
- [CSS Length Units: Relative to the Viewport](https://lenguajecss.com/css/unidades-css/relativas-viewport/)

## Demo

- [x] Arrange a demo session to showcase the implementation and discuss the applied methodologies.

Home Refactor and Responsive changes

screencapture-localhost-8080-2023-11-21-11_40_48
screencapture-localhost-8080-2023-11-21-11_39_54
screencapture-localhost-8080-2023-11-21-11_39_16

[KIN-281]: https://loopcrack.atlassian.net/browse/KIN-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Oswaldo-Chan** [comment]
I have been reviewing the pull request again, and I know that work is still in progress. However, I found a peculiar error in the measurement solutions. I also noticed that the mobile menu is not functioning. Will that be addressed later?

https://github.com/loopcrack-org/Kinub/assets/92545103/1137a194-e67f-4027-9a3c-69c2cba91abb

**Review by CarlosMay7 — CHANGES_REQUESTED** [review]
When you click on a link in the navigation, whether mobile or desktop, it does not perform any action but in general, everything seems to be fine

**Review by CarlosJCD — APPROVED** [review]
Awesome, just please check @Oswaldo-Chan comment about the bug, I also see it but besides that everything works great for me

**Review by CheloChidoone — APPROVED** [review]
Looks good Luis, I'll approve it taking into account you'll make the changes that were already requested

**Review by Oswaldo-Chan — APPROVED** [review]

**Comment by LUGAMAFE** [comment]
> I have been reviewing the pull request again, and I know that work is still in progress. However, I found a peculiar bug in the measurement solutions. I also noticed that the mobile menu is not functioning. Will that be fixed later?
> 
>  video-kinub.mp4

Ready @Oswaldo-Chan

**Comment by LUGAMAFE** [comment]
> When you click on a link in the navigation, whether mobile or desktop, it does not perform any action but in general, everything seems to be fine

Ready @CarlosMay7

**Review by CarlosMay7 — APPROVED** [review]
It works well now, thank you! @LUGAMAFE You can merge it now!

**Review by FernandoJoachin — APPROVED** [review]

**Pull request merged**
