### PR TITLE
KIN-159 Contact Form Data Validation Homepage

### PR DESCRIPTION
**Pull request by FernandoJoachin**
[KIN-159](https://producepay.atlassian.net/browse/KIN-159) Small [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

### Problem

The project requires that the information entered in the contact form on the home page be validated.

### Solution

The implementation of a controller that validates the information entered by the user and returns which fields are incorrect to the view.

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] You must validate the field types
- [ ] You must send the errors in the fields in view.

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Make a submit on the contact form on the home page

[KIN-159]: https://loopcrack.atlassian.net/browse/KIN-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Oswaldo-Chan — APPROVED** [review]

**Review by Cristianpan — CHANGES_REQUESTED** [review]
Add the route to be able to make the post type request and change the error messages from English to Spanish

**Review by Mauriciocr207 — APPROVED** [review]
Well done! This is a correctly validation.

**Review by Oswaldo-Chan — APPROVED** [review]

**Review by Cristianpan — CHANGES_REQUESTED** [review]
You have an error in CtrlEmail on the line 34, please review and make the changes

**Review by Cristianpan — APPROVED** [review]

**Review by Oswaldo-Chan — APPROVED** [review]

**Review by CheloChidoone — CHANGES_REQUESTED** [review]
Todo bien @FernandoJoachin

**Review by CheloChidoone — APPROVED** [review]

**Review by Mauriciocr207 — APPROVED** [review]

**Pull request merged**
