### PR TITLE
KIN-301 Filepond builder and crud test views

### PR DESCRIPTION
**Pull request by Mauriciocr207**
[KIN-301](https://loopcrack.atlassian.net/browse/KIN-301) Large [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

### Problem

It is needed to generate an easy way to create a configuration for the filepond librarie used on the frontEnd and also begin to include a test crud to prove all the file configuration created until now.

### Solution

Create a builder that generates the filepond configuration and create the base of a crud in order to test file configuration

### Requirements checklist

- [x] Create builder logic for filepond config
- [x] Generate a config object for filepond
- [x] The builder must generate the filepond configuration correctly
- [x] The builder must contain the following methods:
   - previewImage - allow the preview of images
   - previewVideo - allow the preview of videos
   - previewPDF - allow the preview of pdf files
   - chunkSize - enable the chunk file manage
   - allowMultipleFiles - allow upload multiple files
   - accetTypesFiles - generates the mime types for setted file extensions
   - isImage - set exclusively image mime types
   - isPDF - set exclusively pdf mime type
   - isVideo - set exclusively video mime type
   - isSVG - set exclusively svg mime type
   - maxSize - set the max file size
   - minSize - set the min file size
   - maxFiles - set the maximum files
   - minFiles - set the minimum files
   - maxDims - allow verify width and heigth of an image (only for images)
- [x] Generates routes, views and methods for CtrlTestFiles and a model to test Files on database in order to create a testing of crud to verify the files functionality

### Testing

- [x] Go to route `/admin/testFiles/` and verify that all views are correctly and try to upload files in create and edit views, proving the filepond builder functionality, and, remember run the project on production mode:  `CI_ENVIRONMENT = production`

This pull request is large due to separate this crud test into filepond builder and the server validation builder (coming on next pull request)

## Demo

[KIN-301]: https://loopcrack.atlassian.net/browse/KIN-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by FernandoJoachin — APPROVED** [review]

**Review by LUGAMAFE — CHANGES_REQUESTED** [review]
XD Hahahahaha forget about this comment, I forgot to put the .env in production.

**Comment by Mauriciocr207** [comment]
> XD Hahahahaha forget about this comment, I forgot to put the .env in production.
Yes, it has happened to me many times. Sorry, I forget to specify the mode on pr description

**Review by LUGAMAFE — APPROVED** [review]
What a nice and clean code @Mauriciocr207 @Cristianpan congratulations!

**Review by CarlosJCD — APPROVED** [review]
Excellent work. I really liked this implementation!

**Review by CheloChidoone — COMMENTED** [review]
Good Job @Mauriciocr207, the code is very clean. 

I ran into an error while testing, when I tried to upload a pdf that has a size of 1.26 MB it did the upload, I'm guessing for that size it might have done it in chunks like for large files because it worked fine for smaller pdfs but for that larger one when it finishes uploading it I got the error that the file is too small but that makes no sense, don't know if the big files are still a work in progress or if they should work

**Comment by Mauriciocr207** [comment]
> Good Job @Mauriciocr207, the code is very clean.
> 
> I ran into an error while testing, when I tried to upload a pdf that has a size of 1.26 MB it did the upload, I'm guessing for that size it might have done it in chunks like for large files because it worked fine for smaller pdfs but for that larger one when it finishes uploading it I got the error that the file is too small but that makes no sense, don't know if the big files are still a work in progress or if they should work

Can you please share me the file by email in order I can prove it. Even if you have a screen or video that could be more descriptive.

**Pull request merged**
