### PR TITLE
KIN-386 Enhance interactive video experience and page scrolling UX

### PR DESCRIPTION
**Pull request by LUGAMAFE**
[KIN-386](https://loopcrack.atlassian.net/browse/KIN-386) Small [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

## Summary
This PR addresses key UX improvements for both mobile and desktop users, with a specific focus on video interaction and page scrolling enhancements. The changes aim to make video playback more engaging and the scrolling experience smoother and more consistent across devices.

## Problem
Previously, the video playback experience was not optimized for user engagement, with playback not starting until fully visible and auto-mute functionality that could detract from user interaction. Additionally, the scrolling experience on the site lacked fluidity and did not account for varying screen sizes, leading to sub-optimal navigation.

## Solution
- **Video Interaction Improvements:**
  - Adjust video settings to initiate playback when 80% visible on the screen.
  - Implement an automatic pause feature for videos not in view.
  - Remove auto-mute functionality and set a reasonable default volume level.
- **Scrolling Experience Enhancements:**
  - Implement 'scroll-snap' for smoother transitions during scrolling.
  - Adjust 'scroll-padding' and 'scroll-margin' values to improve alignment and navigation across different screen sizes.

## Acceptance Criteria
- Video playback automatically starts when 80% visible and pauses when not visible.
- Default volume level is user-friendly, with no auto-muting.
- Scrolling experience is enhanced with smooth transitions and proper alignment.
- All changes are responsive and effective across different screen sizes and devices.

## Requirements Checklist
- [x] Compatibility with major browsers and devices.
- [x]  Performance testing on various devices.
- [x]  User testing to validate UX improvements.

## Testing
- Conduct browser compatibility tests.
- Perform manual testing on different devices to ensure responsive design.

## Demo

https://github.com/loopcrack-org/Kinub/assets/24960025/fcf5ea31-81dd-4262-ae28-b60bea83265f

[KIN-386]: https://loopcrack.atlassian.net/browse/KIN-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CarlosJCD — APPROVED** [review]

**Review by CarlosMay7 — APPROVED** [review]

**Review by CheloChidoone — COMMENTED** [review]
We have a comment to check something @LUGAMAFE, sometimes the video stays muted when we reload the page instead of automatically always starting at the default volume you left it, we don't know why this bug might happen but it happened to both of us.
CC: @Mauriciocr207

**Comment by LUGAMAFE** [comment]
> We have a comment to check something @LUGAMAFE, sometimes the video stays muted when we reload the page instead of automatically always starting at the default volume you left it, we don't know why this bug might happen but it happened to both of us. CC: @Mauriciocr207

You should know this already @CheloChidoone  you can't autoplay a video if the user have not previously interacted with the page, or clicked on it. Here is the explanation:

https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#autoplay_availability

you try to play a video with sound without the user having previously interacted with the page, the play method will throw an exception telling you that it cannot play the video unless it is muted. That's why in my code, if the play method throws an error, it means the user has not previously interacted with the page. Therefore, I set the volume back to 0 and try to replay the video in silence, instead of simply not playing the video.

CC: @Mauriciocr207

**Comment by Mauriciocr207** [comment]
thanks for clarifying it. I was thinking if that was the cause but I wasn't sure.

**Review by CheloChidoone — APPROVED** [review]
Great Job @LUGAMAFE, sorry for the confusion with the other comment, thanks for the clarification

**Review by Mauriciocr207 — APPROVED** [review]

**Review by FernandoJoachin — APPROVED** [review]

**Review by Oswaldo-Chan — APPROVED** [review]

**Pull request merged**
