### PR TITLE
KIN-138 Email Page Layout 

### PR DESCRIPTION
**Pull request by FernandoJoachin**
[KIN-138](https://loopcrack.atlassian.net/browse/KIN-138) Medium [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

email page layout created

### Problem

As a user of the administration panel, I need to be able to view the log of emails sent by the contact forms and technical support form in public view, to be able to have graphical access to them and the related actions.

### Solution

Create the email page layout

### Requirements checklist

- [x] It must display the email records as a table, this table must show the following info for each record: Inquirier name, Inquirier email, Email Type, View Email button and Delete button.
- [x] It must filter the email records by email type.
- [x] It must contain a pagination for the table of email records.

### Testing

- [x] Go to the next route: http://kinub.cm/admin/emails

## Demo

[](https://postimg.cc/FY68pybr)

[KIN-138]: https://loopcrack.atlassian.net/browse/KIN-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CheloChidoone — CHANGES_REQUESTED** [review]
@FernandoJoachin this PR should not be open as we need to complete the merge of this PR [101](https://github.com/loopcrack-org/Kinub/pull/101) first. The Inquirier Name and Email will not be getting stored until that merges and this layout won't work correctly.

CC: @CarlosMay7

**Review by CarlosMay7 — APPROVED** [review]

**Review by LUGAMAFE — APPROVED** [review]
Super!!

**Review by Cristianpan — APPROVED** [review]

**Review by CheloChidoone — APPROVED** [review]
Good job @FernandoJoachin, This layout works fine. We found some bugs in the `contacto` and `soporte tecnico` forms when testing to send the emails, @Mauriciocr207 will share a video of the reproduction of the bugs.

CC: @Mauriciocr207

**Comment by Mauriciocr207** [comment]
> Good job @FernandoJoachin, This layout works fine. We found some bugs in the `contacto` and `soporte tecnico` forms when testing to send the emails, @Mauriciocr207 will share a video of the reproduction of the bugs.
> 
> CC: @Mauriciocr207

Here the bugs
CC: @CheloChidoone 

https://github.com/loopcrack-org/Kinub/assets/70463645/306125c2-294d-4de0-b7f6-eab723abbf72

1.- First, we try to fill all inputs of the contact form, and I clicked 5 times, and we can see that the server save 5 registers of that email.
2.- Also, in the support form, we can see how the last slide goes to left if we click several times, although always send one email, and the server just save one email.

**Review by Mauriciocr207 — APPROVED** [review]

**Comment by CarlosJCD** [comment]
> > Good job @FernandoJoachin, This layout works fine. We found some bugs in the `contacto` and `soporte tecnico` forms when testing to send the emails, @Mauriciocr207 will share a video of the reproduction of the bugs.
> > CC: @Mauriciocr207
> 
> Here the bugs CC: @CheloChidoone
> 
>  bugs_kinub.mp4 
> 1.- First, we try to fill all inputs of the contact form, and I clicked 5 times, and we can see that the server save 5 registers of that email. 2.- Also, in the support form, we can see how the last slide goes to left if we click several times, although always send one email, and the server just save one email. 3.- Also, when you send a form, sometimes send us to the `/admin/emails` route. Maybe because of we were navigating between ``/admin/emails`and`/support` or `/` that is the home page

As this PR is only for the admin panel email page layout, fixes will have to be made on other issues. I will make sure to create their respective bug tickets so that this can be fixed as soon as possible.

**Review by CarlosJCD — APPROVED** [review]

**Pull request merged**
